### ISSUE TITLE
Would it be possible to add support for config file formats?

### ISSUE THREAD

**Issue by e-nikolov** [floyernick/fleep-go#2]
For instance detecting whether a file contains json/yaml/toml?

**Comment by djha-skin** [comment]
Text files do not have magic numbers, the first bytes of the file are simply the first few characters. I doubt this is easily done.

**Comment by e-nikolov** [comment]
Yeah, I guess there is no easy way to do it other than running it through a parser and checking if it failed.

**Comment by ua-nick** [comment]
Unfortunately these formats don't have signatures that would help us to recognize them.
